name: Generate issues report

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Report issues
        run: |
          echo '## Weekly Issue Status' >  ./${{ steps.date.outputs.date }}.md
          gh issue list --json "number,title,state,createdAt,closedAt" >> ./${{ steps.date.outputs.date }}.json
          cat ./${{ steps.date.outputs.date }}.json

      - name: Report workflow runs
        run: |
          gh run list --json "conclusion,createdAt,databaseId,displayTitle,event,headBranch,headSha,name,startedAt,status,updatedAt,url,workflowDatabaseId,workflowName" >> ./${{ steps.date.outputs.date }}_wk.json
          cat ./${{ steps.date.outputs.date }}_wk.json
