name: Generate issues and workflow run report

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Report issues
        run: |
          gh issue list --json >> ./${{ steps.date.outputs.date }}_is.json
          cat ./${{ steps.date.outputs.date }}_is.json

      - name: Report workflow runs
        run: |
          gh run list --json >> ./${{ steps.date.outputs.date }}_wk.json
          cat ./${{ steps.date.outputs.date }}_wk.json
